---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    author: nari
spec:
  type: ClusterIP
  ports: 
    - targetPort: 5432
      port: 5432
  selector: 
    name: postgres-app
...  
