---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres-deployment
  labels:
    name: postgres-app
    author: nari
spec:
  replicas: 1
  selector: 
    matchLabels:
      name: postgres-app
  template:
    metadata: 
      name: postgres-app-pod
      labels: 
       name: postgres-app
    spec:
      containers:
        - name: postgres-app
          image: postgres
          env:
            - name: POSTGRES_USER
              value: naribau
            - name: POSTGRES_PASSWORD
              value: nari
            - name: POSTGRES_DB
              value: mydb
...

