---
apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: nginx-daemonset
  labels:
    app: ghost
spec:
  selector: 
    matchLabels:
      app: ghost
  template:
    metadata:
      name: nginx-pod
      labels:
        app: ghost
    spec:
      containers:
        - name: myngindaemon
          image: nginx
...
  
