---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres-deployment
  labels:
    type: db
spec:
  replicas: 3
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      name: posgres-pod
      labels:
        type: db
    spec:
      containers:
        - name: mypostgress
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES_USER
              valueFrom: 
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_DB
              valueFrom: 
                secretKeyRef:
                  name: postres-secret
                  key : dbname
...


