---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: httpd-deployment
  labels:
    app: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  template:
    metadata: 
      name: httpd-pod
      labels:
        app: webserver
    spec:
      containers:
        - name: myhttpd
          image: httpd
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: worker
                    operator: In
                    values:
                      - narimachine
...

