---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysql-pod
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: nari
            - name: MYSQL_USER
              value: nari
            - name: MYSQL_DATABASE
              value: mydatabase
            - name: MYSQL_PASSWORD
              value: nari
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: my-pvc

...
