---
apiVersion: v1
kind: Pod
metadata: 
  name: httpd-pod
  labels:
    app: httpd
spec:
  containers: 
    - name: myhttpd
      image: httpd
      ports:
        - containerPort: 80
          hostPort: 8080
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: slave2
              operator: In
              values:
                - nari2
...
