---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels: 
    author: nari
spec:
  type: NodePort
  ports: 
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    app: proxy
    author: naribabu
...
