---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: myapp
    author: nari
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: myhttp
  template: 
    metadata:
      name: httpd-pod
      labels: 
        app: myhttp
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 8080
...

