---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: httpd-deployment
  labels:
    app: db
    author: naribabu
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: db
  template:
    metadata: 
      name: httpd-pod
      labels:
        app: db
    spec:
      containers:
        - name: myhttp
          image: httpd
          ports: 
            - containerPort: 80
              hostPort: 9090
...
              

