---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: httpd-deployment
  labels:
    app: db
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: db
  template:
    metadata:
      name: httpd-pod
      labels: 
        app: db
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu: 450m
              memory: 333Mi
...

