---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deployment
  labels: 
    app: proxy
    author: naribabu
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: proxy
  template:
    metadata: 
      name: nginx-pod
      labels:
        app: proxy
    spec:
      containers:
        - name: mynginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 8080
...

