---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: proxy
    author: naribabu
spec: 
  containers:
    - name: mynginx
      image: nginx
      ports: 
        - containerPort: 80
          hostPort: 8080
...
