---
apiVersion: v1
kind: Pod
metadata: 
  name: mysql-pod
  labels:
    app: db
spec:
  containers:
    - name: mysqldb
      image: mysql
      ports:
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
...
