---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ghost-daemon
  labels: 
    name: myapp
spec:
  selector:
    matchLabels:
      app: cms
  template:
    metadata:
      name: ghost-pod
      labels:
        app: cms
    spec:
      containers: 
        - name: ghost
          image: ghost
          env: 
            - name: NODE_ENV
              value: development
...

