---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jenkins-deployment
  labels:
    app: myjen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      name: myjenkins
      labels: 
        app: webserver
    spec:
      containers:
        - name: myjenkins
          image: jenkins/jenkins
          ports:
            - containerPort: 8080
              hostPort: 9090
...
