---
apiVersion: v1
kind: Pod
metadata: 
  name: postgres-pod
  labels:
    app: mydb
spec:
  containers:
    - name: mypostgres
      image: postgres
      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: u1
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: p1
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: d1
...

