---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    type: db
spec:
  containers:
    - name: mypostgres
      image: postgres
      env:
        - name: POSTGRES_USER
          value: nari
        - name: POSTGRES_PASSWORD
          value: nari9
        - name: POSTGRES_DB
          value: mydb
...
