---
apiVersion: v1
kind: Pod
metadata: 
  name: httpd-pod
  labels:
    type: webserver
spec:
  containers: 
    - name: myserver
      image: httpd
      ports:
        - containerPort: 80
          hostPort: 8080
      resources:
        requests:
          cpu: 200m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 128Mi
...

