---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployemnt
  labels:
    type: webserver
spec:
  replicas: 2
  selector: 
    matchLabels:
      type: webserver
  template:
    metadata: 
      name: httpd-pod
      labels:
        type: webserver
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
... 

