---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service 
  labels:
    author: narihome
spec: 
  type: ClusterIP
  ports: 
    - targetPort: 5432
      port: 80
  selector:
    type: db
...
