---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: db
spec:
  clusterIP: None
  ports:
    - port: 3306
      protocol: TCP
      name: tcp
  selector:
    app: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  labels:
    app: db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db
  serviceName: mysql
  template:
    metadata:
      name: nginx-pod
      labels:
        app: db
    spec:
      containers: 
        - name: mydb
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: nari
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata: 
        name: mysql-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 300Mi
...
