---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: premium-retain-waitforconsumer
provisioner: kubernetes.io/azure-disk
parameters: 
  storageaccounttype: Premium_LRS
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
...


