---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: proxy
spec:
  containers:
    - name: mynginx
      image: nikkiteja/nginx13
      volumeMounts:
        - name: nginx-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx-volume
      emptyDir: {}
...
